##
## SfynxCoreBundle configuration
##       
#sfynx_core:  
#    cache_dir:
#        media: "%kernel.root_dir%/cachesfynx/Media/"     
#    cookies:
#        date_expire: true
#        date_interval:  %pi_cookie_lifetime% # 604800 PT4H  604800
#        application_id: sfynx  
#    translation:
#        defaultlocale_setting: false        
#    permission:
#        restriction_by_roles: false
#        authorization:
#            prepersist: true
#            preupdate: true
#            preremove: true
#        prohibition:
#            preupdate: true
#            preremove: true


## Stof Doctrine Configuration
#stof_doctrine_extensions:
#    default_locale: %locale%
#    translation_fallback: true
#    persist_default_translation: true
#    orm:
#        default:
#            tree: true
#            timestampable: true
#            sluggable: true
#            loggable: true
#            sortable: true
#            translatable: true


##
## SonataDoctrineORMAdminBundle configuration
##
#sonata_doctrine_orm_admin:
#    # default value is null, so doctrine uses the value defined in the configuration
#    entity_manager: ~
#
#    templates:
#        form:
#            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
#        filter:
#            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
#        types:
#            list:
#                array:      SonataAdminBundle:CRUD:list_array.html.twig
#                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
#                date:       SonataAdminBundle:CRUD:list_date.html.twig
#                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
#                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
#                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
#                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
#                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
#                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
#                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
#                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
#                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
#
#            show:
#                array:      SonataAdminBundle:CRUD:show_array.html.twig
#                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
#                date:       SonataAdminBundle:CRUD:show_date.html.twig
#                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
#                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
#                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
#                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
#                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
#                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
#                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
#                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig


##               
## Doctrine Configuration
##
#doctrine:
#    dbal:
#        types:
#            json: Sonata\Doctrine\Types\JsonType    
#        default_connection:       default
#        connections:
#            default:
#                driver:   %database_driver%
#                host:     %database_host%
#                port:     %database_port%
#                dbname:   %database_name%
#                user:     %database_user%
#                password: %database_password%
#                charset:  UTF8
#                mapping_types:
#                      enum:       string
#                      varbinary:  string
#                      tinyblob:   text
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
#        mappings:
#            ## http://brentertainment.com/other/docs/book/doctrine/orm.html
#            ## http://symfony.com/fr/doc/current/reference/configuration/doctrine.html
#            #MyBundle1: ~
#            #MyBundle2: yml
#            #MyBundle3: { type: annotation, dir: Entity/ , alias: BundleAlias}
#            #MyBundle4: { type: xml, dir: Resources/config/doctrine/mapping , alias: BundleAlias }
#            #MyBundle5:
#            #    mapping:              true
#            #    type:                 ~
#            #    dir:                  ~
#            #    alias:                ~
#            #    prefix:               ~
#            #    is_bundle:            ~     
#            FOSUserBundle: ~
#            StofDoctrineExtensionsBundle: ~
#            SonataMediaBundle: ~
#            OrAppOrAdminBundle: ~
#            OrAppOrGedmoBundle: ~
#            SfynxAuthBundle: ~
#            #SfynxAuthBundle:
#            #    type: xml
#            #    dir: "%kernel.root_dir%/../src/OrApp/OrUserBundle/Resources/config/doctrine/mapping"
#            #    prefix: Sfynx\AuthBundle\Entity
#            #    alias: SfynxAuthBundle
#            #    is_bundle: false             
#            SfynxTranslatorBundle: ~
#            SfynxMediaBundle: ~        
#            SfynxCmfBundle: ~
#            PiAppGedmoBundle: ~
#            translatable:
#                type: annotation
#                alias: Gedmo
#                prefix: Gedmo\Translatable\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#            loggable:
#                type: annotation
#                alias: Gedmo
#                prefix: Gedmo\Loggable\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#            tree:
#                type: annotation
#                alias: Gedmo
#                prefix: Gedmo\Tree\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
#        metadata_cache_driver: array # array|apc
#        query_cache_driver: array
#        result_cache_driver: array
##        metadata_cache_driver:
##            type: memcache
##            host: localhost
##            port: 11211
##            class: Doctrine\Common\Cache\MemcacheCache
##            instance_class: Memcache         
##        query_cache_driver: 
##            type: memcache
##            host: localhost
##            port: 11211
##            class: Doctrine\Common\Cache\MemcacheCache
##            instance_class: Memcache          
##        result_cache_driver:
##            type: memcache
##            host: localhost
##            port: 11211
##            class: Doctrine\Common\Cache\MemcacheCache
##            instance_class: Memcache  